apiVersion: v1
kind: Service
metadata:
  name: k8s-helloworld-dotnetcore-service
  labels:
    app: k8s-helloworld-dotnetcore
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
  selector:
    app: k8s-helloworld-dotnetcore
